Name=input("Enter name:")
RollNo=int(input("Enter Roll Number:"))
Course=input("Enter Course Name:")
Age=int(input("Enter Age:"))
Academic_percent=float(input("Enter percentage:"))
print("---------------------------")
print("Student Management System")
print("Student Name:",Name)
print("Student Roll Number:",RollNo)
print("Course Name:",Course)
print("Student Age:",Age)
print("Student Academic Percentage:",Academic_percent)
